### ISSUE TITLE
Warning: Did not expect server HTML to contain a <script> in <html>.

### ISSUE THREAD

**Issue by hugo** [remix-run/starter-express#14] opened 2021-02-07 15:14 UTC
After cloning, installing, and running this example repo I see the following in the console:
<details>
<summary>
Warning: Did not expect server HTML to contain a <script> in &lt;html&gt;.
</summary

```
Warning: Did not expect server HTML to contain a <script> in <html>.
head
html
App@http://localhost:3000/build/root.js:11:26
RemixErrorBoundary
RemixRoute@http://localhost:3000/build/_shared/__remix-run/react-fd118932.js:528:14
Routes@http://localhost:3000/build/_shared/__remix-run/react-fd118932.js:690:27
Router@http://localhost:3000/build/_shared/react-router-44425546.js:8:283
RemixErrorBoundary
RemixEntry@http://localhost:3000/build/_shared/__remix-run/react-fd118932.js:341:24
RemixBrowser@http://localhost:3000/build/_shared/__remix-run/react-fd118932.js:709:32
```
</details>

This does not occur if if I run `npm run build` and `npm run start` so it appears to be something to do with the development server.

**Comment by nicolasrenon** [comment] 2021-03-16 00:19
I haven't found yet the root cause, but that's just telling us about a mismatch between what's rendered by the server and what is expected by React on the client at rehydration time.

**Comment by mjackson** [comment] 2021-04-29 23:38
Thanks for the issue, but we are archiving this repo. We have a new `npm init remix` command that we are recommending people use to get started instead of the starter repos, so I'm closing all the issues here.

Hopefully you got this sorted out, but if not please come and find us on Discord for stuff like this. You can find the link in the Support tab on remix.run. Thanks!

**Closed as completed by mjackson** 2021-04-29 23:38 UTC
